### ISSUE TITLE
formula should also manage libvirtd.conf

### ISSUE THREAD

**Issue by aboe76** [saltstack-formulas/libvirt-formula#16]
It would be nice if the libvirt-formula also manages libvirtd.conf

something like: https://github.com/webscale-formulas/libvirt-formula

**Comment by gravyboat** [comment]
I'm all for stealing that code if the license permits it.

**Comment by aboe76** [comment]
@gravyboat , I think that will be no problem, same license as the salstack-formulas...

**Comment by aboe76** [comment]
ok created pull request see #17

**Comment by gravyboat** [comment]
Looks good to me, my only concern is backwards compatibility as people will have to update some of their stuff. @babilen or @iggy could you weigh in? These changes look good to me.

**Comment by babilen** [comment]
Agree, merged.
