### ISSUE TITLE
InSpec tests fail on new `fedora-31` pre-salted image

### ISSUE THREAD

**Issue by myii** [saltstack-formulas/libvirt-formula#64]
@baby-gnu A quick note for you, while I've been testing the new pre-salted images across all of our formulas:

* https://travis-ci.org/myii/libvirt-formula/jobs/602614950#L4956-L4990

You can use the links at the top of that page (i.e. the commit) to get details about the new `fedora-31` image, should you desire to get to the bottom of this.  Let me know how you'd like to proceed.

**Comment by baby-gnu** [comment]
Thanks, I'll try locally and fix it.

Regards.

**Comment by baby-gnu** [comment]
Ok, this is due to systemd socket activation, the settings in `/etc/libvirt/libvirtd.conf` is ignored:

```
#################################################################
#
# UNIX socket access controls
#

# Set the UNIX domain socket group ownership. This can be used to
# allow a 'trusted' set of users access to management capabilities
# without becoming root.
#
# This setting is not required or honoured if using systemd socket
# activation.
#
# This is restricted to 'root' by default.
#unix_sock_group = "libvirt"

# Set the UNIX socket permissions for the R/O socket. This is used
# for monitoring VM status only
#
# This setting is not required or honoured if using systemd socket
# activation.
#
# Default allows any user. If setting group ownership, you may want to
# restrict this too.
#unix_sock_ro_perms = "0777"

# Set the UNIX socket permissions for the R/W socket. This is used
# for full management of VMs
#
# This setting is not required or honoured if using systemd socket
# activation.
#
# Default allows only root. If PolicyKit is enabled on the socket,
# the default will change to allow everyone (eg, 0777)
#
# If not using PolicyKit and setting group ownership for access
# control, then you may want to relax this too.
#unix_sock_rw_perms = "0770"

# Set the UNIX socket permissions for the admin interface socket.
#
# This setting is not required or honoured if using systemd socket
# activation.
#
# Default allows only owner (root), do not change it unless you are
# sure to whom you are exposing the access to.
#unix_sock_admin_perms = "0700"

# Set the name of the directory in which sockets will be found/created.
#
# This setting is not required or honoured if using systemd socket
# activation with systemd version >= 227
#
#unix_sock_dir = "/var/run/libvirt"
```

It will take a little more effort than I thought.

**Comment by myii** [comment]
Here is the upgrade matrix (only one failure):

* https://travis-ci.org/myii/libvirt-formula/builds/604702449

Here are all of the rest of the instances (12 to choose from):

* https://travis-ci.org/myii/libvirt-formula/builds/604809986

**Comment by myii** [comment]
@baby-gnu OK, I've switched `fedora` and `opensuse` (between `2019.2` and `2018.3`) and pushed the updated matrix to the formula.  This will workaround the issue for the time being.  This issue can remain open as a reminder that `fedora-31` will require some work.

**Comment by baby-gnu** [comment]
Thanks @myii.

From time to time I run a `kitchen verify` locally to see how the non travis-tested environment are working.

**Comment by baby-gnu** [comment]
For `fedora-31`, I think the solution will be provided by the `Running the formula without specific pillar should provide the OS default configuration` from #33.
