### ISSUE TITLE
Breaks when the osmajorrelease grain is missing.

### ISSUE THREAD

**Issue by andrew-vant** [saltstack-formulas/libvirt-formula#8]
The error message is:

`Rendering SLS 'base:libvirt' failed: Jinja variable 'dict object' has no attribute 'osmajorrelease`

This is on Ubuntu 14.04 with salt version 2015.8.1. The offending line is [here](https://github.com/saltstack-formulas/libvirt-formula/blob/master/libvirt/map.jinja#L11). I think the check it's performing was just added recently.

Looking at the grains I do have, my first impulse is to change it to check grains.osrelease_info[0] instead. But I'm not that familiar with what grains exist where. If my configuration is missing osmajorrelease, it's possible others are missing osrelease_info. I'm not sure if there's an os version grain that's guaranteed to always exist.

(also, the service name detection that line is intended to perform gets the wrong result on my ubuntu, but that's easily fixable by populating pillar:libvirt:lookup:service, wheras the failed key lookup makes the state not work at all.)

**Comment by gravyboat** [comment]
the osmajorrelease grain only exists for redhat based systems as far as I'm aware. I've mentioned this issue in the PR that added this so we can get some more info from them on the Debian systems.

**Comment by Sjd-Risca** [comment]
For sure he grain osmajorrelease is supported since version 2015.5.3 of saltstack on Debian system.

> (also, the service name detection that line is intended to perform gets the wrong result on my ubuntu

That line refers only to Debian, not Ubuntu systems.
 
I think that the correct way ti solve the issue would be to add a parametrization on Ubuntu that not is still missing in the formula.

```bash
# apt-cache policy salt-minion 
salt-minion:
  Installed: 2015.5.3+ds-1~bpo70+2
  Candidate: 2015.5.3+ds-1~bpo70+2
  Package pin: 2015.5.3+ds-1~bpo70+2
  Version table:
 *** 2015.5.3+ds-1~bpo70+2 1001
        500 http://debian.saltstack.com/debian/ wheezy-saltstack/main amd64 Packages
        100 /var/lib/dpkg/status

# salt 'test' grains.item osmajorrelease
test:
    ----------
    osmajorrelease:
        8

```

**Comment by gravyboat** [comment]
Thanks for the input @Sjd-Risca. @andrew-vant if you want to prep a PR to do a simple check for the OS type that would be great.
